version: '3.4'

services:

  builder:
    command: /usr/local/bin/build.sh
    image: advent-go-build
    build:
      context: .
      target: builder
    volumes:
    - ./src:/go/src/advent

  test2017:
    command: go test
    image: advent-go-build
    working_dir: /go/src/advent/2017
    volumes:
    - ./src:/go/src/advent

  test2018:
    command: go test
    image: advent-go-build
    working_dir: /go/src/advent/2018
    volumes:
    - ./src:/go/src/advent

  main:
    image: advent-go
    build:
      context: .
